apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging-discovery
  labels:
    component: elasticsearch
    role: all
spec:
  ports:
  - port: 9300
    name: transport
    protocol: TCP
  clusterIP: None
  selector:
    component: elasticsearch
    role: all
