apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    role: all
spec:
  ports:
  - port: 9200
    name: http 
  selector:
    component: elasticsearch
    role: all
